version: '3.8'  # Especifica la versión de Docker Compose

services:
  # Servicio RabbitMQ con el plugin de administración
  rabbitmq:
    image: rabbitmq:3-management  # Incluye el plugin de administración
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"      # Puerto AMQP estándar para RabbitMQ
      - "${RABBITMQ_PORT_ADMIN}:15672"  # Puerto para la interfaz de administración
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - app-network

  # Servicio Zookeeper (requerido para Kafka)
  # Descomenta si decides usar Kafka en el futuro
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:7.5.1  # Especifica una versión estable
  #   container_name: zookeeper
  #   hostname: zookeeper
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #     ZOOKEEPER_SYNC_LIMIT: 2
  #   ports:
  #     - "2181:2181"
  #   volumes:
  #     - zookeeper_data:/var/lib/zookeeper
  #   networks:
  #     - app-network

  # Servicio Kafka Broker
  # Descomenta si decides usar Kafka en el futuro
  # kafka:
  #   image: confluentinc/cp-kafka:7.5.1  # Especifica una versión estable
  #   container_name: kafka
  #   hostname: kafka
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     # Asegúrate de definir estas variables en tu .env si decides usar Kafka
  #     KAFKA_CONSUMER_GROUP: ${KAFKA_CONSUMER_GROUP}
  #     KAFKA_CONSUMER_GROUP_DLQ: ${KAFKA_CONSUMER_GROUP_DLQ}
  #   volumes:
  #     - kafka_data:/var/lib/kafka/data
  #   networks:
  #     - app-network

volumes:
  rabbitmq_data:
    driver: local
  # zookeeper_data:
  #   driver: local
  # kafka_data:
  #   driver: local

networks:
  app-network:
    driver: bridge
